/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Child { 'id' : bigint, 'name' : string }
export interface Letter {
  'id' : bigint,
  'content' : string,
  'childId' : bigint,
  'parentName' : string,
}
export interface Photo {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'childId' : bigint,
  's3Link' : string,
}
export interface _SERVICE {
  'addChild' : ActorMethod<[string], bigint>,
  'addLetter' : ActorMethod<[string, bigint, string], bigint>,
  'addPhoto' : ActorMethod<[string, string, bigint, string], bigint>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getAllPhotosByTitle' : ActorMethod<[], Array<Photo>>,
  'getChild' : ActorMethod<[bigint], Child>,
  'getLetter' : ActorMethod<[bigint], Letter>,
  'getPhoto' : ActorMethod<[bigint], Photo>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];