/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'childId' : IDL.Nat,
  's3Link' : IDL.Text,
});
export const Child = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const Letter = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'childId' : IDL.Nat,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addChild' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addLetter' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getAllPhotosByTitle' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getChild' : IDL.Func([IDL.Nat], [Child], ['query']),
  'getLetter' : IDL.Func([IDL.Nat], [Letter], ['query']),
  'getPhoto' : IDL.Func([IDL.Nat], [Photo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'childId' : IDL.Nat,
    's3Link' : IDL.Text,
  });
  const Child = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const Letter = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'childId' : IDL.Nat,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    'addChild' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addLetter' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getAllPhotosByTitle' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getChild' : IDL.Func([IDL.Nat], [Child], ['query']),
    'getLetter' : IDL.Func([IDL.Nat], [Letter], ['query']),
    'getPhoto' : IDL.Func([IDL.Nat], [Photo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };